// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OceanTech.Database;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace OceanTech.Migrations
{
    [DbContext(typeof(OceanTechContext))]
    partial class OceanTechContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OceanTech.Models.GameDiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("gd_int_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Jogou")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("gd_int_Jogou");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("us_int_id");

                    b.Property<DateTime>("dataJogo")
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("gd_dat_DataJogou");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TB_GS_GameDiario", (string)null);
                });

            modelBuilder.Entity("OceanTech.Models.Pontuacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("pc_int_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PontuacaoMensal")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("pc_int_pontuacaoMensal");

                    b.Property<decimal>("UsuarioId")
                        .HasColumnType("NUMBER(25)")
                        .HasColumnName("us_int_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TB_GS_Pontuacao", (string)null);
                });

            modelBuilder.Entity("OceanTech.Models.PontuacaoDiaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("pd_int_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameDiarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("gd_int_id");

                    b.Property<int>("Valor")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("pd_int_valor");

                    b.HasKey("Id");

                    b.HasIndex("GameDiarioId");

                    b.ToTable("TB_GS_PontuacaoDiarias", (string)null);
                });

            modelBuilder.Entity("OceanTech.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("us_int_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ativo")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ativo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("us_string_email");

                    b.Property<DateTime?>("Inscricao")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("us_dat_inscricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("NVARCHAR2(225)")
                        .HasColumnName("us_string_nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("us_string_senha");

                    b.HasKey("Id");

                    b.ToTable("TB_GS_Usuario", (string)null);
                });

            modelBuilder.Entity("OceanTech.Models.GameDiario", b =>
                {
                    b.HasOne("OceanTech.Models.Usuario", "Usuario")
                        .WithMany("GameDiarios")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK_GS_GameDiarioUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("OceanTech.Models.Pontuacao", b =>
                {
                    b.HasOne("OceanTech.Models.Usuario", "Usuario")
                        .WithMany("Pontuacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GS_PontuacaoUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("OceanTech.Models.PontuacaoDiaria", b =>
                {
                    b.HasOne("OceanTech.Models.GameDiario", "GameDiario")
                        .WithMany("PontuacaoDiaria")
                        .HasForeignKey("GameDiarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GS_PontuacaoDiariaGameDiario");

                    b.Navigation("GameDiario");
                });

            modelBuilder.Entity("OceanTech.Models.GameDiario", b =>
                {
                    b.Navigation("PontuacaoDiaria");
                });

            modelBuilder.Entity("OceanTech.Models.Usuario", b =>
                {
                    b.Navigation("GameDiarios");

                    b.Navigation("Pontuacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
